"""isbn, year for books

Revision ID: 811602fb9e2f
Revises: 
Create Date: 2023-11-19 22:59:33.623849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811602fb9e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('publication_year')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
